#!/bin/bash

# author: Dmitry Binyuk <dbinyuk@griddynamics.com>
# description: script for creating URL for adding new node on GoGrid
# created: 22.01.2014 13:34
# last changed: 23.01.2014 13:59


source ./libgg

while getopts "c:i:r:n:d:" OPT; do
    case $OPT in
	c) GGC=$OPTARG;;
    i) IMAGE=$OPTARG;;
	r) RAM=$OPTARG;;
	n) NAME=$OPTARG;;
	d) DESCR=$OPTARG;;
    esac
done

DESCR=${DESCR:-""}
NAME=${NAME?"NAME is not defined"}
IMAGE=${IMAGE?"IMAGE is not defined"}
RAM=${RAM?"RAM is not defined"}
IP=$(./gg_ip_list)

METHOD='/grid/server/add?'

function buildBaseURL {
	#creating URL which contains of name image ram description and auth parameters

	#https://wiki.gogrid.com/index.php/API:grid.server.add

        URL="$1$2&sig=$3&name=$4&image=$5&ram=$6&format=$7&v=$8&api_key=$9&ip=${10}&description=${11}"
}

getSig
buildBaseURL $SERVER $METHOD $SIG $NAME $IMAGE $RAM $FORMAT $VERSION $APIKEY $IP $DESCR
# id	name	description	ip.id	ip.ip	ip.subnet	ip.public
getURL $URL| awk -F, '!/#/ {print $1, $2, $5}'

