#!/bin/bash

# author: Dmitry Binyuk <dbinyuk@griddynamics.com>
# description: script for creating URL for deleting node on GoGrid by id
# created: 22.01.2014 13:38
# last changed: 23.01.2014 14:02

source ./libgg

while getopts "c:i:" OPT; do
    case $OPT in
	c) GGC=$OPTARG;;
    i) IMAGE=$OPTARG;;
    esac
done

IMAGE=${IMAGE?"IMAGE is not defined"}

#FORMAT=xml
METHOD='/grid/server/delete?'

function buildBaseURL {
	#creating URL which contains of name image and auth parameters

	#https://wiki.gogrid.com/index.php/API:grid.server.delete

        URL="$1$2&sig=$3&id=$4&format=$5&v=$6&api_key=$7"
}

# Get to work

getSig
buildBaseURL $SERVER $METHOD $SIG $IMAGE $FORMAT $VERSION $APIKEY
getURL $URL

