#!/bin/bash

# print_opts solution


while getopts "c:n:f:" OPT; do
    case $OPT in
	c) GGC=$OPTARG;;    
        n) NUMITEMS=$OPTARG;;
    esac
done

GGC=${GGC:-"$HOME/.gg"}

[ "$DEBUG" = "1" ] && echo DEBUG: gg_config: "$GGC"

source "$GGC"
APIKEY=${APIKEY?"APIKEY is not defined"}
SECRET=${SECRET?"SECRET is not defined"}
NUMITEMS=${NUMITEMS:-"1"}
IPSTATE="Unassigned"
IPTYPE="Public"
GTIME=`date +%s`

SERVER='https://api.gogrid.com/api'
VERSION='1.0'
FORMAT=${FORMAT:-"csv"}
METHOD='/grid/ip/list?'

function getMD5sum {
        HASH=$1$2$3
        SIG=`echo -n $HASH | md5sum | cut -d' ' -f1`
}


function buildBaseURL {
        #without array, cleaner in bash
        URL="$1$2&sig=$3&num_items=$4&ip.state=$5&ip.type=$6&format=$7&v=$8&api_key=$9"
}


function getURL {
        # have curl fail silently and spit out error code to STDERR
        curl -f --silent $1
}

# Get to work

getMD5sum $APIKEY $SECRET $GTIME
buildBaseURL $SERVER $METHOD $SIG $NUMITEMS $IPSTATE $IPTYPE $FORMAT $VERSION $APIKEY
getURL $URL| awk -F, '!/#/ {print $2}'

