#!/bin/bash

# author: Dmitry Binyuk <dbinyuk@griddynamics.com>
# description: script for creating URL for taking list of nodes on GoGrid
# created: 23.01.2014 13:42
# last changed: 23.01.2014 14:11

source ./libgg

while getopts "c:" OPT; do
    case $OPT in
        c) GGC=$OPTARG;;
    esac
done

METHOD='/grid/server/list?'

function buildBaseURL {
	#creating URL which contains of gogrid configure and auth parameters

	#https://wiki.gogrid.com/index.php/API:grid.server.list

	URL="$1$2&sig=$3&format=$4&v=$5&api_key=$6"
}

# Get to work

getSig
buildBaseURL $SERVER $METHOD $SIG $FORMAT $VERSION $APIKEY
getURL $URL

