#!/bin/bash

# author: Dmitry Binyuk <dbinyuk@griddynamics.com>
# description: helper functions for GoGrid REST API
# created: 22.01.2014 13:34
# last changed: 23.01.2014 18:23

GGC=${GGC:-"$HOME/.gg"}
source "$GGC"

APIKEY=${APIKEY?"APIKEY is not defined"}
SECRET=${SECRET?"SECRET is not defined"}
SERVER='https://api.gogrid.com/api'
VERSION='1.0'
FORMAT=csv

function getSig {
	#calculate signature for gg rest api request

	# sets SIG env variable value
	GTIME=`date +%s`
	HASH="${APIKEY}${SECRET}${GTIME}"

	SIG=`echo -n $HASH | md5sum | cut -d' ' -f1`
}

function getURL {
	# have curl fail silently and spit out error code to STDERR
	#taking data from internet resource by URL

	#$1 - URL from which takes data for current script

	curl -s -f $1
}


